# Generated by Django 4.0.2 on 2022-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowduser',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
