# Generated by Django 4.0.2 on 2022-03-24 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_remove_crowduser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='org_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stu_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
