# Generated by Django 4.0.2 on 2022-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_orguserprofile_user_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguserprofile',
            name='org_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orguserprofile',
            name='org_intro',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orguserprofile',
            name='org_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
