# Generated by Django 4.0.2 on 2022-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_orguserprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
