# Generated by Django 4.0.2 on 2022-04-10 19:25

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_alter_crowduser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[user_auth.models.validate_birth]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.DateField(validators=[user_auth.models.validate_admission]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(validators=[user_auth.models.validate_birth]),
        ),
    ]
