# Generated by Django 4.0.2 on 2022-04-10 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questionnaire.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0010_alter_orguserprofile_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Please type the title here.', help_text='Please enter the title', max_length=100)),
                ('description', models.TextField(default='Please type the description here.', help_text='Please type a short description.(around 200 words)', max_length=200)),
                ('deadline', models.DateField(default=datetime.date.today, validators=[questionnaire.models.validate_deadline])),
                ('post_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('questionsize', models.IntegerField(default='Please enter the number of questions here.', help_text='Please enter an integer number. (Minimum is 1 and Maximum is 30)', validators=[questionnaire.models.validate_size])),
                ('questiontype', models.CharField(choices=[('mc', 'Multiple Choice'), ('lq', 'Long Question'), ('sc', 'Scoring'), ('gf', 'Google Form')], default='mc', max_length=6)),
                ('question', models.TextField(default='Please type the question here.', help_text='Type each question delimited by `;`, e.g. 1.How old are you?; 2.Where do you live?', max_length=5000)),
                ('publishable', models.BooleanField(default=True)),
                ('host', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Ans', models.TextField(default='Please type the answer here.', help_text='Type each answer delimited by `;`, e.g. 1.6 years old; 2.Hong Kong', max_length=3000)),
                ('Respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.studentprofile')),
                ('questionnaire', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
        ),
    ]
