# Generated by Django 4.0.2 on 2022-04-11 16:33

from django.db import migrations, models
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='exp_finish',
            field=models.CharField(default='Please type the expected finishing time here.', help_text='Please enter the the expected finishing time', max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='Ans',
            field=models.TextField(default='Please type the answer here.', help_text='Type each answer delimited by `;`, e.g. 6 years old; Hong Kong', max_length=3000),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.TextField(default='Please type the question here.', help_text='Type each question delimited by `;`, e.g. How old are you?; Where do you live?', max_length=5000),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionsize',
            field=models.IntegerField(default='Please enter the number of questions here.', help_text='Please enter an integer number. (Minimum is 1 and Maximum is 10)', validators=[questionnaire.models.validate_size]),
        ),
    ]
