# Generated by Django 4.0.2 on 2022-04-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamformation', '0002_alter_teammates_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamformation',
            name='publishable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammates',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
