# Generated by Django 4.0.2 on 2022-04-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamformation', '0003_teamformation_publishable_teammates_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamformation',
            name='team_img',
        ),
    ]
