# Generated by Django 4.0.2 on 2022-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamformation', '0004_remove_teamformation_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamformation',
            name='contact',
            field=models.TextField(default='Please type the contact here.', help_text='Please type your contact. (Email , Phone number, etc...)', max_length=200),
        ),
        migrations.AlterField(
            model_name='teamformation',
            name='description',
            field=models.TextField(default='Please type the description here.', help_text='Please type a short description.(around 200 words)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='teamformation',
            name='link',
            field=models.TextField(blank=True, default='Please type the links here.', help_text='Please enter the links that you need.(if available)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teamformation',
            name='requirements',
            field=models.TextField(default='Please type the requirements here.', help_text='Please type your requirements that team members need.(around 100 words)', max_length=200),
        ),
        migrations.AlterField(
            model_name='teamformation',
            name='self_intro',
            field=models.TextField(default='Please type something about yourself here.', help_text='Please type a short self-introduction.(around 100 words)', max_length=500),
        ),
        migrations.AlterField(
            model_name='teamformation',
            name='title',
            field=models.CharField(default='Please type the title here.', help_text='Please enter the title', max_length=200),
        ),
    ]
